<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="1" failures="0" file="classes_user_tests.py" name="classes_user_tests.Test-20190510174504" skipped="0" tests="1" time="0.012" timestamp="2019-05-10T17:45:04">
	<testcase classname="classes_user_tests.Test" file="unittests\classes_user_tests.py" line="6" name="test_md5" time="0.012" timestamp="2019-05-10T17:45:04">
		<error message="name 'utils' is not defined" type="NameError">
<![CDATA[Traceback (most recent call last):
  File "c:\users\mathe\documents\shared\github\eswqa\unittests\classes_user_tests.py", line 7, in test_md5
    md5 = utils.md5("12345")
NameError: name 'utils' is not defined
]]>		</error>
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
</testsuite>
