<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="1" failures="0" file="unittest/suite.py" name="unittest.suite._ErrorHolder-20190510175802" skipped="0" tests="1" time="0.000" timestamp="0001-01-01T00:00:00">
	<testcase classname="setUpClass (classes_utils_tests" name="Test)" time="0.000" timestamp="0001-01-01T00:00:00">
		<error message="name 'self' is not defined" type="NameError">
<![CDATA[Traceback (most recent call last):
  File "c:\users\mathe\documents\shared\github\eswqa\unittests\classes_utils_tests.py", line 10, in setUpClass
    self.ut = Utils.Utils()
NameError: name 'self' is not defined
]]>		</error>
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
</testsuite>
