<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="1" failures="0" file="unittest/loader.py" name="unittest.loader._FailedTest-20190510175052" skipped="0" tests="1" time="0.011" timestamp="2019-05-10T17:50:52">
	<testcase classname="unittest.loader._FailedTest" file="..\..\..\..\appdata\local\programs\python\python36\Lib\unittest\loader.py" line="33" name="classes_utils_tests" time="0.011" timestamp="2019-05-10T17:50:52">
		<error message="Failed to import test module: classes_utils_tests
Traceback (most recent call last):
  File &quot;c:\users\mathe\appdata\local\programs\python\python36\Lib\unittest\loader.py&quot;, line 153, in loadTestsFromName
    module = __import__(module_name)
  File &quot;c:\users\mathe\documents\shared\github\eswqa\unittests\classes_utils_tests.py&quot;, line 7, in &lt;module&gt;
    import classes.utils as Utils
ModuleNotFoundError: No module named 'classes'
" type="ImportError">
<![CDATA[ImportError: Failed to import test module: classes_utils_tests
Traceback (most recent call last):
  File "c:\users\mathe\appdata\local\programs\python\python36\Lib\unittest\loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "c:\users\mathe\documents\shared\github\eswqa\unittests\classes_utils_tests.py", line 7, in <module>
    import classes.utils as Utils
ModuleNotFoundError: No module named 'classes'

]]>		</error>
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
</testsuite>
