<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="2" failures="0" file="unittest/loader.py" name="unittest.loader._FailedTest-20190510205723" skipped="0" tests="2" time="0.007" timestamp="2019-05-10T20:57:23">
	<testcase classname="unittest.loader._FailedTest" file="/usr/lib/python3.6/unittest/loader.py" line="33" name="classes_utils_tests" time="0.006" timestamp="2019-05-10T20:57:23">
		<error message="Failed to import test module: classes_utils_tests
Traceback (most recent call last):
  File &quot;/usr/lib/python3.6/unittest/loader.py&quot;, line 153, in loadTestsFromName
    module = __import__(module_name)
  File &quot;/home/matheus/github/eswqa/unittests/classes_utils_tests.py&quot;, line 5, in &lt;module&gt;
    import utils as Utils
ModuleNotFoundError: No module named 'utils'
" type="ImportError">
<![CDATA[ImportError: Failed to import test module: classes_utils_tests
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/home/matheus/github/eswqa/unittests/classes_utils_tests.py", line 5, in <module>
    import utils as Utils
ModuleNotFoundError: No module named 'utils'

]]>		</error>
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
	<testcase classname="unittest.loader._FailedTest" file="/usr/lib/python3.6/unittest/loader.py" line="33" name="classes_user_tests" time="0.000" timestamp="2019-05-10T20:57:23">
		<error message="Failed to import test module: classes_user_tests
Traceback (most recent call last):
  File &quot;/usr/lib/python3.6/unittest/loader.py&quot;, line 153, in loadTestsFromName
    module = __import__(module_name)
  File &quot;/home/matheus/github/eswqa/unittests/classes_user_tests.py&quot;, line 5, in &lt;module&gt;
    from user import User as User
ModuleNotFoundError: No module named 'user'
" type="ImportError">
<![CDATA[ImportError: Failed to import test module: classes_user_tests
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/home/matheus/github/eswqa/unittests/classes_user_tests.py", line 5, in <module>
    from user import User as User
ModuleNotFoundError: No module named 'user'

]]>		</error>
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
</testsuite>
